.TH "GFXfont" 3 "Mon Jan 15 2018" "AdafruitTFTSPIDriver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GFXfont
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBbitmap\fP"
.br
.ti -1c
.RI "\fBGFXglyph\fP * \fBglyph\fP"
.br
.ti -1c
.RI "uint8_t \fBfirst\fP"
.br
.ti -1c
.RI "uint8_t \fBlast\fP"
.br
.ti -1c
.RI "uint8_t \fByAdvance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AdafruitTFTSPIDriver from the source code\&.
