.TH "GFXglyph" 3 "Mon Jan 15 2018" "AdafruitTFTSPIDriver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GFXglyph
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBbitmapOffset\fP"
.br
.ti -1c
.RI "uint8_t \fBwidth\fP"
.br
.ti -1c
.RI "uint8_t \fBheight\fP"
.br
.ti -1c
.RI "uint8_t \fBxAdvance\fP"
.br
.ti -1c
.RI "int8_t \fBxOffset\fP"
.br
.ti -1c
.RI "int8_t \fByOffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AdafruitTFTSPIDriver from the source code\&.
