.TH "TSButtonVars" 3 "Mon Jan 15 2018" "AdafruitTFTSPIDriver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSButtonVars
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AdafruitTFTButton\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBx\fP"
.br
.ti -1c
.RI "int16_t \fBy\fP"
.br
.ti -1c
.RI "uint16_t \fBw\fP"
.br
.ti -1c
.RI "uint16_t \fBh\fP"
.br
.ti -1c
.RI "uint16_t \fBoutlineColor\fP"
.br
.ti -1c
.RI "uint16_t \fBfillColor\fP"
.br
.ti -1c
.RI "uint16_t \fBtextColor\fP"
.br
.ti -1c
.RI "char \fBlabel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A collection of variables needed to create a button\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t TSButtonVars::fillColor"
Button color > 
.SS "uint16_t TSButtonVars::h"
Button height > 
.SS "char TSButtonVars::label"
Single ASCII character to be displayed on button > 
.SS "uint16_t TSButtonVars::outlineColor"
Outline of button > 
.SS "uint16_t TSButtonVars::textColor"
Color of the button label > 
.SS "uint16_t TSButtonVars::w"
Button width\&. > 
.SS "int16_t TSButtonVars::x"
x-coordinate of button > 
.SS "int16_t TSButtonVars::y"
y-coordinate of button > 

.SH "Author"
.PP 
Generated automatically by Doxygen for AdafruitTFTSPIDriver from the source code\&.
